### ISSUE TITLE
Add a tab to see dead jobs

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/verk_web#10]
Similar implementation to `Retries`

**Comment by krasio** [comment]
Makes sense - https://github.com/krasio/verk_web/commit/360e4571e454baeec4e4bf24fabfe55c56d252f3?
If it does I may try to DRY it a little bit to reduce duplication with Retires and submit a pull request.

**Comment by edgurgel** [comment]
It makes total sense! Yeah it would cool to reuse parts of the retries/dead code. Sorry for the late reply

**Comment by keyan** [comment]
@edgurgel @krasio, any updates on this? I was about to open a PR and realized krasio's branch made the exact same changes. Anything holding this back? Happy to help push it along. We would really like to have this feature before doing too much more production volume.

**Comment by krasio** [comment]
Nothing really holding it back except me being busy and procrastinating it 😞. Feel free to take over using either my branch or starting from scratch.

**Comment by keyan** [comment]
Do you have any ideas/pointers for reusing the retries code? I can see why we'd want to, as it would also help with #12, but I am not quite sure what the implementation would look like.

**Comment by edgurgel** [comment]
I wouldn't stress a lot about reusing this code. We can do this as a "phase 2" approach. I'm fine with a bit of duplicated code for now.

**Comment by keyan** [comment]
We can close this :)

**Comment by edgurgel** [comment]
Closed by https://github.com/edgurgel/verk_web/pull/31
