### ISSUE TITLE
Add a retry button

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/verk_web#11]
Add a retry button so we can retry instantly some jobs that failed

**Comment by keyan** [comment]
Just a heads up that I am working on this, albeit a bit slowly as I am just back from holiday.

**Comment by edgurgel** [comment]
Cool `Verk` was released with the new script you added! 🎉

**Comment by keyan** [comment]
I looked at this a bit. I was trying to add a new button but I'm not sure how to send the form data [here](https://github.com/edgurgel/verk_web/blob/cecfa6253ef8d80705bc9ed64d12e5cadf2380ba/web/templates/retries/index.html.eex#L7) using a different method than `DELETE`.

It doesn't seem like [`Phoenix.HTML.Form.form_for`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#form_for/4) allows for this? Perhaps someone with more knowledge of Phoenix.HTML can offer some advice?

Here is the new method needed for the controller: https://github.com/edgurgel/verk_web/compare/master...keyan:kp_retry_button?expand=1

**Comment by edgurgel** [comment]
Cool @keyan, I will have a look this weekend! Thank you for starting this work. 

BTW, I'm keen to release Verk & Verk Web 1.0 before 2017 comes. You are helping heaps 👍
