### ISSUE TITLE
Add a tab to see scheduled jobs

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/verk_web#12]
Similar to Retries

**Comment by edgurgel** [comment]
This won't work with hundreds of queues (which is a valid use case). I think the best approach here is to have this functionality per queue as it is today. 

Retries and dead jobs are sitting at the same Redis structure and that's not the cause for queues.

**Comment by edgurgel** [comment]
I completely mixed things up! Scheduled jobs are a single set! My bad!

**Comment by keyan** [comment]
Fixed by #44, thanks @jakecraige!
