### ISSUE TITLE
Mounting VerkWeb on a path of an existing Endpoint

### ISSUE THREAD

**Issue by mindreframer** [edgurgel/verk_web#14]
This is more to start a discussion if this is a wanted feature. 

Here is my current implementation, that so far looks promising... 
- https://github.com/ruby2elixir/verk_web/tree/mount_plug

The inspiration came from: 
- http://neuvians.io/2016/03/15/using-a-phoenix-app-as-a-dependency/
- https://github.com/maxneuvians/phoenix_dependency_test

this problem is not properly solved yet: 
- https://www.bountysource.com/issues/23491390-correctly-scope-static-file-paths-generated-in-forwarded-endpoints

What was done: 
- check-in generated static files into Git (simpler deployment)
- provide the plug for mounting
- adjust readme 
- remove VerkWeb.Endpoint from application to start

It depends on my fork of Verk atm, that's why it makes no sense to open a pull request... 
@edgurge what are your thoughts about this feature?

**Comment by edgurgel** [comment]
I'm super keen to have this feature. I'm keen to release a new Verk version soon (possibly today) with your PR so we can start working on this feature.

 Does this seem like a good plan? 

Thank you very much for starting to work on this :)

**Comment by mindreframer** [comment]
@edgurgel yeah, that sounds like a good plan, waiting for the new version to be released

**Comment by edgurgel** [comment]
Released! Oh I forgot to add that I would still like to support running `:verk_web` as simply as adding the application to the applications list. And for now treat the case of mounting the endpoint as an option that you can configure (effectively changing `server: false` on the user config.exs or exrm configuration).

The release is out there. I will start testing and playing around with your branch soon. Thanks again for the contribution :+1:

**Comment by edgurgel** [comment]
Done by @mindreframer  #15 :tada:
