### ISSUE TITLE
Add `will be retried at` date to jobs on retry queue

### ISSUE THREAD

**Issue by alissonsales** [edgurgel/verk_web#22]
Using `x from now` format.

**Comment by keyan** [comment]
I took a look at this and it looks easy on the VerkWeb side, just adding another column to the [retries template here](https://github.com/edgurgel/verk_web/blob/e3828057937bd0707f76d36b08befd494cdde49d/web/templates/retries/index.html.eex#L14). But it requires support on the Verk end. I see a couple options:

1. Appending the `retry_at` time to the `job` before adding to the `retry` queue. We would merge the extra item to the job map [here](https://github.com/edgurgel/verk/blob/f8da5e941d77e86a261ad8ae54e81f203892e6bf/lib/verk/retry_set.ex#L21).

2. Adding a new method to similar to `Verk.SortedSet.range/4` [here](https://github.com/edgurgel/verk/blob/f8da5e941d77e86a261ad8ae54e81f203892e6bf/lib/verk/sorted_set.ex#L55), but that includes the "SCORE" for each item:

```
ZRANGE retry start stop WITHSCORES
```

Then we'd have to add a new method to `VerkWeb.RetriesView` that takes the list of jobs/scores and merges them in the template.

Any feedback on these approaches? Any preference for one or the other?

**Comment by keyan** [comment]
I should add that I plan on using http://timeago.yarp.com/ or something similar as suggested in #21.

**Comment by edgurgel** [comment]
I like the "WITHSCORES" approach 👍 

Maybe `Verk.SortedSet.range_with_score` ? (I'm not the most creative person 😶 )

**Comment by keyan** [comment]
This is now resolved.
