### ISSUE TITLE
Authentication for UI

### ISSUE THREAD

**Issue by thousandsofthem** [edgurgel/verk_web#24]
Is there a way to customize mounting options? Trying to integrate it into phoenix app.
Would be nice to protect Verk UI with simple http auth or something 

In exq_ui i can simply add necessary stuff via pipelines:
https://github.com/akira/exq_ui#using-with-plug

**Comment by edgurgel** [comment]
That's a great question! I will summon @mindreframer as he's the author behind the custom Verk Endpoint https://github.com/edgurgel/verk_web/issues/14

I'm not a Plug, Phoenix hardcore user so I won't be of much help here but I suspect it's doable?

**Comment by thousandsofthem** [comment]
@mindreframer no news so far?

It is surely doable, but i'm not that experienced to do it by myself :(

**Comment by mitchellhenke** [comment]
I needed a simple solution for http basic auth, and came up with this: https://github.com/edgurgel/verk_web/compare/master...mitchellhenke:http-basic-auth?expand=1

I'm not sure that it's complete or clean enough for inclusion in verk_web, but it functions as expected.

**Comment by thousandsofthem** [comment]
Great solution, thanks!
It surely worth inclusion into verk_web. Well... i know minor issue with it:
https://github.com/CultivateHQ/basic_auth/issues/7
Basically: it adds ability to configure credentials after compilation phase (via env vars e.g.)
Solution: see `basic_auth`s source code

Also, suggestion: just use `basic_auth` module

**Comment by keyan** [comment]
@mitchellhenke, I think your PR looks good! Could you open a PR? If you'd rather not I am happy to pull your branch and try to get it merged.

**Comment by edgurgel** [comment]
Closed by #37
