### ISSUE TITLE
Upgrade to verk_web 0.13.3 crashes my application on startup

### ISSUE THREAD

**Issue by keyan** [edgurgel/verk_web#40]
Still trying to triage this, but upgrading to 0.13.3 breaks my application by preventing startup.

Startup crash log: https://gist.github.com/keyan/29f1c503cc3de1865bbc9531e33692e8
My `mix.lock`: https://gist.github.com/keyan/3d372b125579e684116a5f0f9713eb09

I might have to make some application changes on my end in order to work with the new version. At the very least I think the changes were large enough and added additional features and so warrant a minor version bump.

**Comment by edgurgel** [comment]
yeah I tend to agree. If we had major versions this would definitely become a major version. My bad! 

I will try to replicate the issue. 

Just by looking at the logs it looks like the gen event handler couldn't be added to the manager as the Watcher crashed... 🤔

**Comment by keyan** [comment]
> it looks like the gen event handler couldn't be added to the manager as the Watcher crashed

Yeah. At first I thought this was because we weren't starting `:watcher` in the application list?

https://github.com/edgurgel/verk_web/blob/f0075c559e081ce6df881416be54ddfb045de8e3/mix.exs#L26

But adding it there didn't help. I presume it is being started by Verk?

Anyhow, thanks for taking a look. To help I created this barebones app that gets the same error: https://github.com/keyan/example_app

**Comment by edgurgel** [comment]
Oh yeah that's the issue. Since the Verk supervisor is now started by the main application we can't start that watcher/gen event handler before the Verk Supervisor is up 🤔 

We didn't notice this issue during dev because the supervisor starts Verk.Supervisor first :(

*tableflip*

**Comment by edgurgel** [comment]
One option is to start the handler when the websocket is open to watch events (for the live dashboard). I will take a look at it now.

**Comment by edgurgel** [comment]
cc/ @alissonsales

**Comment by edgurgel** [comment]
![verk_web___hex](https://cloud.githubusercontent.com/assets/30873/21468929/83a61372-ca93-11e6-9661-00a60884f0dc.png)

I've also retired 0.13.3.
