### ISSUE TITLE
Warning message seen.

### ISSUE THREAD

**Issue by nguyenchiencong** [edgurgel/verk_web#43]
When running the phoenix server. I see plenty of those messages:
[warn] Ignoring unmatched topic "rooms:jobs" in xxx.UserSocket

As a beginner to elixir phoenix, some help would be awesome.

Thanks

**Comment by edgurgel** [comment]
Thanks for the report. We recently added a phoenix channel to do the dashboard stats. I'm not sure why the warning is showing. cc/ @alissonsales

**Comment by immon** [comment]
You should change `socket "/socket", MyApp.UserSocket` to  `socket "/socket", VerkWeb.UserSocket` in MyApp.Endpoint module to make websocket working and get rid of the warning.

In web/static/js/socket.js#L6 there is a hardcoded path to /socket and by default this path is handled by MyApp.UserSocket.
Socket.js should use the path specified in `use VerkWeb.Mount, path: "/verk"`

**Comment by edgurgel** [comment]
Thanks for the info, @immon !

**Comment by keyan** [comment]
Looks like @immon's advice resolved @nguyenchiencong's problem. Closing this.
