### ISSUE TITLE
Publish docker image on docker hub

### ISSUE THREAD

**Issue by tlvenn** [edgurgel/verk_web#53]
It would be neat to add a Dockerfile and publish to docker hub a standalone verk web server.

**Comment by edgurgel** [comment]
Hey @tlvenn, thanks for opening the issue but I have no plans to maintain a docker image for a standalone usage of Verk Web. 

Verk Web is supposed to be used as a library as part of an application. If somebody wants to maintain a repo with a docker application that runs Verk Web, feel free to link to the `README.md`

Thanks!

**Comment by tlvenn** [comment]
Thanks for the feedback @edgurgel , I will create one then and report back ;)

**Comment by edgurgel** [comment]
Awesome! 👍
