### ISSUE TITLE
error in template

### ISSUE THREAD

**Issue by salisbury-espinosa** [edgurgel/verk_web#59]
** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: {:a, "b"}

https://github.com/edgurgel/verk_web/blob/master/web/templates/dead/index.html.eex#L66

**Comment by edgurgel** [comment]
Thanks for the bug report! Fixed by https://github.com/edgurgel/verk_web/commit/d74e0310db9d0d0fcf3408f712a8748758ff5d88 . I'm trying to publish a new version but hex timed out for me -.-

**Comment by edgurgel** [comment]
```
Publishing package...
[#########################] 100%
:timeout
Publishing failed
```
