### ISSUE TITLE
Dashboard: Incorrect internal links

### ISSUE THREAD

**Issue by thousandsofthem** [edgurgel/verk_web#61]
Internal links in the VerkWeb are behaving weirdly, see screenshot:

![2017-09-19 20-56-03](https://user-images.githubusercontent.com/736279/30607287-1a7743b8-9d7d-11e7-9094-ada3ed5a7db6.png)

* `page_path(@conn, :index)` -> `/` (incorrect)
* `mount_static_path(@conn, "/js/app.js")` -> `/verk/js/app.js` (correct)

Details:
* phoenix 1.3.0
* verk 1.1.0
* verk_web 1.0.2 (same behavior for master as well)
* plug 1.4.3

mounted into endpoint via 
```elixir
defmodule App.Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :app
  use VerkWeb.Mount, path: "/verk"
  ...
```
I have an older project with phoenix 1.2 and verk 0.13.5 and everything works as expected.
git diff between these versions don't show any related changes so it's probably behavior change on  phoenix/plug side. 

Did anyone encounter something similar? Thoughts on debugging?

P.S. related - https://github.com/edgurgel/verk_web/blob/master/web/views/layout_view.ex#L5 - that's why `mount_static_path` works well.

**Comment by edgurgel** [comment]
🤔 Thanks for the bug report! We are still using Phoenix 1.2 😶

**Comment by thousandsofthem** [comment]
Looks like it's fixed in https://github.com/edgurgel/verk_web/pull/66 , the only gotcha is to not forget to update config. Just tested it - works well for me

**Comment by edgurgel** [comment]
Awesome! I will release a new version with all the changes 👍 Thanks for the feedback

**Comment by edgurgel** [comment]
1.2.0 is out!
