### ISSUE TITLE
Support for Phoenix 1.3.0

### ISSUE THREAD

**Issue by alexcastano** [edgurgel/verk_web#64]
Hello,

It seems it does not work for the newest versions of Phoenix:

```
Failed to use "phoenix" (version 1.3.0) because            
  phoenix_live_reload (version 1.1.1) requires ~> 1.0      
  verk_web (version 1.1.0) requires ~> 1.2.1               
  mix.exs specifies ~> 1.3.0    
```

Any plan or solutions about this?

Thanks for your time

**Comment by edgurgel** [comment]
Oh hey we are having some issues with Phoenix 1.3 https://github.com/edgurgel/verk_web/issues/61 I'm not using Phoenix 1.3 currently so it may take some time to move this forward.

**Comment by thousandsofthem** [comment]
https://github.com/edgurgel/verk_web/pull/66 fixed it, looks like. not released yet though master works well.

**Comment by edgurgel** [comment]
Verk 1.2 is out!
