### ISSUE TITLE
Add a "Run Job" on Scheduled jobs

### ISSUE THREAD

**Issue by seanculver** [edgurgel/verk_web#70]
Hello,

Thanks for writing this very useful library!

I have a use case where I want to manually run the scheduled job earlier than the scheduled time through the interface.

I imagine a button next to the details button on the scheduled jobs tab. This would have a javascript "Are you sure" alert and then just enqueue the scheduled job immediately.

I'd be interested in writing a PR for this if you think it would be something you'd want to add.

**Comment by edgurgel** [comment]
That would be an amazing addition! The code would be pretty similar to the Retry now I suspect as they have a similar structure (sorted sets etc). If you need any guidance feel free to open a PR and we can get this done 👍

**Comment by seanculver** [comment]
See: https://github.com/edgurgel/verk_web/pull/71

**Comment by edgurgel** [comment]
v1.4.0 is out! I just tested! Thanks!
