### ISSUE TITLE
Phoenix 1.4 mount issue

### ISSUE THREAD

**Issue by emhagman** [edgurgel/verk_web#75]
Hi,

The newest release of phoenix (including cowboy2) no longer has the method `Phoenix.Router.Route.forward/4`. I receive the following error trying to redirect to `/verk`.

```
function Phoenix.Router.Route.forward/4 is undefined or private
```

It is happening inside the `plug/mount.ex` file in the `defp forward` method.

EDIT: For now, I got around it by adding this to my router directly.
```
  scope "/", VerkWeb do
    forward("/verk", Endpoint)
  end
```

**Comment by DiodonHystrix** [comment]
I guess this has been fixed with the latest release?
