### ISSUE TITLE
Cowboy 2 support?

### ISSUE THREAD

**Issue by adityaU** [edgurgel/verk_web#78]
```
Failed to use "cowboy" (version 2.6.1) because
  plug_cowboy (version 2.0.1) requires ~> 2.5
  verk_web (versions 1.0.0 to 1.4.2) requires ~> 1.0
  mix.lock specifies 2.6.1
```

**Comment by edgurgel** [comment]
I've already made it work once by simply overriding the dependency forcing cowboy etc but I think we should just support it without these changes.

**Comment by DiodonHystrix** [comment]
I guess with the latest release this has been resolved?
